IF(${TORRENT} MATCHES ON)
	SET(TORRENT_DOWNLOADER ON)
	SET(DOWNLOADER ON)
ENDIF(${TORRENT} MATCHES ON)

IF(${TORRENT_DOWNLOADER} MATCHES ON)
	SET(TORRENT ON)
	SET(DOWNLOADER ON)
ENDIF(${TORRENT_DOWNLOADER} MATCHES ON)

IF(${HTTP_DOWNLOADER} MATCHES ON)
	SET(DOWNLOADER ON)
ENDIF($HTTP_DOWNLOADER} MATCHES ON)