SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
FIND_PACKAGE( Boost 1.35 COMPONENTS filesystem thread system )
INCLUDE_DIRECTORIES(${INCLUDE_DIRECTORIES} ${Boost_INCLUDE_DIR})
SET(CMAKE_FIND_LIBRARY_PREFIXES "")
