IF(${TORRENT_DOWNLOADER} MATCHES ON)
	SET(DOWNLOADER ON)
ENDIF(${TORRENT_DOWNLOADER} MATCHES ON)

IF(${HTTP_DOWNLOADER} MATCHES ON)
	SET(DOWNLOADER ON)
ENDIF(${HTTP_DOWNLOADER} MATCHES ON)

ADD_DEFINITIONS(-DNDEBUG)
